[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true
[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "MSAP1gen"
version = "0.0.1"
authors = [
  { name="Walter van Rossem", email="walter_v_rossem@hotmail.com" },
]
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pyyaml",
    "astropy",
    "h5py",
    "platoconstants@git+https://git.ias.u-psud.fr/plato_pdc_public/platoconstants.git",
    "wsssss",
    "packaging"
]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Astronomy",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/waltervrossem/MSAP1gen"
Issues = "https://github.com/waltervrossem/MSAP1gen/issues"
