# PLATO Solar-like Light-curve Simulator (PSLS) configuration file, V 1.8 (compatible with V 1.8 or higher)

# Observation conditions
Observation:
  QuarterDuration :  [90.,90.,90.] #  quarter duration [days] ; the total duration of the simulation is the sum of the quarter durations
  MasterSeed : 1704040900 # Master seed of the pseudo-random number generator
  Gaps:
    Enable: 1
    Seed: -1 # Seed of the pseudo-random number generator used to generate the gaps
    # inter-quarter gaps
    InterQuarterGapDuration: 3.  # Duration of the inter-quarter interruptions (days) ; inter-quarter gaps are ignored if zero or negative value
    # Random gaps
    RandomGapDuration:  0. # Duration of the random interruptions  (minutes) ; random gaps are ignored if zero or negative value
    RandomGapTimeFraction: 0.5 # fraction (in %) of the total time lost by the random gaps ; random gaps are ignored if zero or negative value
    RandomGapStep: 0.  # Random gap step in %
    # Periodic interruptions
    PeriodicGapCadence: 5. # Cadence of the periodic interruptions (in days) ; periodic gaps are ignored if zero or negative value
    PeriodicGapDuration: 20. # Duration of each periodic interruption  (minutes) ; periodic gaps are ignored if zero or negative value
    PeriodicGapJitter: 2. # Jitter in the time instants the periodic gaps occur (in hours) ; normal distribution assumed
    PeriodicGapStep: 0.  # Periodic gap step in %

# Instrument parameters
Instrument:
  Sampling : 25. # Sampling  cadence [s] (nominal value: 25s)
  IntegrationTime : 21. # Integration time [s]
  GroupID: [1,2,3,4] # IDs of the camera groups included in the simulation, example [2,3] to simulate group 2 and group 3
  NCamera : 6 # Number of cameras per group (1 -> 6)
  TimeShift : 6.25 # Time shift between camera groups [s]
  RandomNoise:
    Enable: 1
    Type: PLATO_SIMU #  either 'User' or 'PLATO_SCALING' or 'PLATO_SIMU'.
# 'User': the NSR value is specified by the user (see below) 
# 'PLATO_SCALING': the NSR value is obtained by interpolating, at the given magnitude, the NSR scaling relation expected for PLATO
# 'PLATO_SIMU': the NSR is taken from realistic simulated ligth-curves (stored in the systematics error table, see below) and vary with the mask shapes and thus then the latter are updated
    NSR :  73. # User-specified Noise to Signal Ratio [ppm in one hour] for a single camera. This value takes into account all random noises but does not include systematic errors.
  Systematics:
    Enable : 1
# The binary file containing the systematics parameters:
    Table : PSLS_DIR/systematics/PLATO_systematics_BOL_V2.npy  # representative for the sample P5 stars, with mask updates during the quarter
#    Table :  PSLS_DIR/systematics/PLATO_systematics_BOL_FixedMask_V2.npy # representative for the sample P5 stars, with fixed mask during the quarter
#    Table :  PSLS_DIR/systematics/PLATO_systematics_BOL_P1_V2.npy # representative for the sample P1 stars
    Version: 2  # Version of the table
    DriftLevel: any  # Amplitude of the drift:  'min', 'low', 'medium', 'high', 'max' or 'any'. Applicable only for Version>0
    Seed: -1 # Seed of the pseudo-random number generator used for the systematic errors. Negative value if controlled by MasterSeed

# Stellar parameters
Star:
  Mag : 10. #  V magnitude (John V magnitude). The V magnitude is converted into the PLATO P magnitude using the star effective temperature following Marchiori et al (2019, A&A)'s Teff-magnitude relation.
  ID : 12069449  #  star ID (arbitrary number)
  ModelType: single  # Type of  pulsation model, this can be either 'UP', 'grid', 'grid-old' 'single', or 'text'.
  # The option 'grid-old' shall be used with the old type of grid, the new one being stored in HDF5 files
  ModelDir: PSLS_DIR/models/ # Directory containing the pulsation models (a single ADIPLS file, a grid of ADIPLS files,  or a simple TEXT file, see below)
  ModelName: 0012069449  # Name of the input pulsation model, to be specified when ModelType = 'single' or 'text'.
  # The input  pulsation model can be either a .gsm file (generated by ADIPLS)
  #  a simple TEXT file
  # or an HDF5 file storing a grid of CESAM2K models.
  # In the cas of a TEXT file, the latter shall provide the mode properties (in 3 columns: frequency, width and height). Mode frequencies and mode widths are in muHz and mode heights are in ppm^2/muHz. For the mode heights a "single-sided" spectrum is assumed.
  ES : ms  # Evolutionary status: 'ms' for the main-sequence phase, 'sg' for the sub-giant phase, 'rg' for redgiants (Red Giant Branch or clump stars)
  Teff : 5750.  # Effective temperature [K]
  Logg : 4.353 # Surface gravity, ignored for the UP
  SurfaceRotationPeriod :  0. # Surface rotation period [days]
  CoreRotationFreq :  0. # Core rotation frequency [muHz], this is by definition Omega/2pi*1e6 where Omega is the angular rate [rad/s], included only for l=1 modes
  Inclination : 0. # Inclination angle [deg.],  Inclination=0, the rotation axis points toward the observer

# Oscillations
Oscillations:
  Enable: 1
  numax : 179.3 # frequency at maximum power [muHZ], used only with the UP or when ModelType = text
  delta_nu : 13.68 # Mean large separation [muHz], used only with the UP or when ModelType = text, -1 if you want this parameter to be derived from a scaling relation
  DPI : 80.58 # Asymptotic values of the gravity mode period spacing [s], used only with the UP, -1 if you don't want mixed modes to be included
  q : 0.15 # Mixed mode coupling factor, used only with the UP
  SurfaceEffects: 1 # Include near-surface effects in mode frequencies, not implemented for the UP
  Seed: -1 # Seed of the pseudo-random number generator used to simulate the oscillations component

# Activity
Activity :
  # Stochastic component (Lorentzian component, see Samadi et al 2019)
  # Not included when ModelType = "UP"
  # Should not be used when spot modulation is enabled (see below)
  Enable: 1
  Sigma : 40. # Amplitude of the activity component [ppm]
  Tau : 0.2 # Timescale of the activity component [days]
  Seed: -1 # Seed of the pseudo-random number generator used to simulate the (stochastic) activity component

  # Spot component (Dorren (1987)'s model)
  # Note that the rotational modulation of the spot(s) is controlled by the surface rotation period
  # and the inclination angle of the rotation axis ; these both parameters are fixed
  # in the "Star" section of the configuration file (see above).
  Spot:
    Enable: 0
    dOmega: 0. # Differential rotation, dimensionless
    MuStar: 0.59 # Limb darkening coefficient of the star (a linear limb darkening law is assumed)
    MuSpot: 0.78 # Limb darkening coefficient of the spot
    Radius: [2.5,2.5,2.5] # Spots radii, in degrees, as many values as spots modelled
    Latitude: [0.0, 20.0, 40.0] # Spots latitudes, in degrees
    Longitude: [0.0, 0.0, 0.0] # Spots latitudes, in degrees
    Lifetime: [10,30,50] # lifetime of the spot in days
    TimeMax: [-1,-1, -1]   # The time of maximum spot contrast, in days.  Negative value if you want to be drawn randomly
    Contrast: [0.7, 0.8, 0.6]  # Maximum contrast of the spot (flux of the spot in units of unspotted stellar flux), dimensionless
    Modulation: 0.   # Modulation period of the spot radii (days), ignored if negative or zero value ; default: 0
    Seed: -1 # Seed of the pseudo-random number generator used to generate TimeMax. Negative value if controlled by MasterSeed

  # Flare component, based on a prescription established by F. Baudin
  Flare:
    Enable: 0
    MeanPeriod: 2 # mean period btw  2 flares (days)
    Amplitude: 2500.  # mean flares amplitudes (ppm) ; the flares amplitudes are drawn from Normal distribution centred at FlareAmplitude and with a dispersion of FlareAmplitude / 10
    UpDown:  0.1 # Ratio of the time taken for the flow to rise to the time taken for the flow to fall
    MeanDuration: -1 # mean flare duration (days). If negative,  MeanDuration = MeanPeriod/5
    DurationDispersion: -1 # dispersion in the flare duration (days). If negative,  DurationDispersion = MeanPeriod/20
    Seed: -1 # Seed of the pseudo-random number generator used to generate the flares. Negative value if controlled by MasterSeed


Granulation : 
  Enable: 1
  Type: 1 #  0-> single Lorentzian component ; 1-> Kallinger et al(2014)'s empirical model
  Seed: -1 # Seed of the pseudo-random number generator used to simulate the granulation component

# Planetary Transit (Mandel & Agol (2002)'s algorithm)
Transit : 
  Enable: 1
  PlanetRadius : 0.5   # in jupiter radii
  OrbitalPeriod : 10.  # in days
  PlanetSemiMajorAxis : 1.  # in A.U.
  OrbitalAngle : 0. # in deg
  LimbDarkeningCoefficients: [0.25,0.75] # 2 or 4 coefficients can be used. 2 for a quadratic law and 4 for a non-linear law


External:  # external stellar component: any additional stellar variability imposed by the user using an external TEXT file
  Enable: 0
  FilePath: PSLS_DIR/examples/external_example.txt # path to a TEXT file containing a time-series of relative flux variation (in ppm)
            # the first column shall be the time in second and the second one the relative flux variation in ppm.
            # The time-series shall cover the simulation duration
            # The flux is assumed to be normalized to one:   S(t) = 1. + dS * 1e-6
            # where S(t) is the stellar component and dS the corresponding relative flux variation in ppm